# Generated by Django 5.1.2 on 2024-11-11 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('eletiva', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
                'db_table': 'disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Alunos',
                'db_table': 'alunos',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('disciplinas', models.ManyToManyField(to='IConline.disciplinas')),
            ],
            options={
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('disciplinas', models.ManyToManyField(to='IConline.disciplinas')),
            ],
            options={
                'verbose_name_plural': 'Professores',
                'db_table': 'professores',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('semestre', models.CharField(max_length=6)),
                ('descricao', models.TextField()),
                ('link', models.URLField()),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IConline.cursos')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='IConline.disciplinas')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IConline.professores')),
            ],
            options={
                'verbose_name_plural': 'Materiais',
                'db_table': 'materiais',
            },
        ),
    ]
