# Generated by Django 5.1.2 on 2024-11-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('IConline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, to='IConline.disciplinas'),
        ),
        migrations.AlterField(
            model_name='professores',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, to='IConline.disciplinas'),
        ),
    ]
