# Generated by Django 5.1.2 on 2024-11-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IConline', '0002_alter_cursos_disciplinas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('prova', 'Prova'), ('lista', 'Lista'), ('projeto', 'Projeto')], max_length=255),
        ),
    ]
